### ISSUE TITLE
Can't open the game, core.dll is there

### ISSUE THREAD

**Issue by LilyBergonzat** [ExileLord/GH3-Plus#1]
I just followed the installation instructions. core.dll is in the PLUGINS folder which is in the root folder of Guitar Hero III.

The only thing I didn't do is replace the tapping note sprites, but I'm guessing this has no impact on the game.

What should I do to fix that? Are there log files somewhere so I can find what's broken?

**Comment by kolatra** [comment]
Copied from Exile's comment section.

Try installing the Visual C++ Redistributable for Visual Studio 2015 and tell me if that works. If a debug.txt is being generated when you run the game please post that as well.﻿

**Comment by LilyBergonzat** [comment]
I tried to install it when I first witnessed the problem. It asked me if I wanted to repair (meaning I already had it on my computer). I clicked "repair", just to be sure. Also, no debug.txt has been generated.
